const baseState={year:1,season:0,speed:1,paused:false,population:1000000,treasury:680,approval:64,stability:72,gdp:12.4,inflation:4.2,turn:0,log:[{text:'تُوّج أحمد ملكًا وبدأ عهد جديد',date:'اليوم الأول'}],groups:{workers:{name:'العمال',count:310000,approval:61,income:4200},professionals:{name:'المهنيون',count:190000,approval:68,income:8900},merchants:{name:'التجار',count:90000,approval:65,income:12400},farmers:{name:'المزارعون',count:220000,approval:59,income:3600},students:{name:'الطلاب',count:140000,approval:74,income:1100},elite:{name:'النخبة',count:50000,approval:70,income:28000}},ministries:{health:{name:'الصحة',minister:'د. ليان الحكيم',fund:84,performance:73},education:{name:'التعليم',minister:'مريم النور',fund:76,performance:69},interior:{name:'الداخلية',minister:'فارس المنصور',fund:92,performance:78},economy:{name:'الاقتصاد',minister:'سليم الراوي',fund:68,performance:65},housing:{name:'الإسكان',minister:'نادر عمران',fund:57,performance:61},defense:{name:'الدفاع',minister:'اللواء عاصم',fund:110,performance:81}},cities:[{name:'مدينة التاج',pop:320000,jobs:83,services:86,mood:72},{name:'الواحة الخضراء',pop:210000,jobs:69,services:73,mood:65},{name:'ميناء النور',pop:185000,jobs:78,services:70,mood:68},{name:'سهول المملكة',pop:165000,jobs:61,services:64,mood:59},{name:'حصن الحدود',pop:120000,jobs:58,services:60,mood:63}],army:{soldiers:42000,readiness:81,morale:76,equipment:72},nations:[{name:'جمهورية الشمال',relation:61,trade:38},{name:'اتحاد الجزر',relation:78,trade:65},{name:'إمارة الشرق',relation:44,trade:22},{name:'ممالك الغرب',relation:69,trade:51}]};
let state=JSON.parse(localStorage.getItem('kingdomState')||'null')||structuredClone(baseState);
const decisions=[
 {id:'wage',tag:'الاقتصاد',title:'رفع الحد الأدنى للأجور',text:'تطالب نقابات العمال برفع الأجور 12% لمواجهة تكاليف المعيشة.',choices:[{label:'اعتماد الزيادة',effects:{treasury:-35,approval:8,inflation:1.1,gdp:.3},groups:{workers:13,merchants:-4},result:'احتفل العمال بالمرسوم، بينما حذّر التجار من ارتفاع التكاليف.'},{label:'زيادة محدودة 5%',effects:{treasury:-14,approval:3,inflation:.4},groups:{workers:5},result:'استقبل الشارع القرار بحذر، لكنه خفّف الاحتقان.'},{label:'رفض الطلب',effects:{approval:-7,stability:-5,inflation:-.2},groups:{workers:-14,elite:3},result:'بدأت النقابات في تنظيم احتجاجات متفرقة.'}]},
 {id:'hospital',tag:'الصحة',title:'مستشفى ملكي في سهول المملكة',text:'تقترح وزارة الصحة مستشفى جديدًا يخدم المناطق الأقل تنمية.',choices:[{label:'البناء فورًا',effects:{treasury:-90,approval:9,stability:3},city:{index:3,services:17,mood:10},result:'بدأت أعمال البناء ووصلت فرق طبية إلى الإقليم.'},{label:'عيادات متنقلة',effects:{treasury:-25,approval:4},city:{index:3,services:7,mood:5},result:'انطلقت العيادات، وهي حل سريع لكنه مؤقت.'},{label:'تأجيل المشروع',effects:{approval:-5,treasury:5},city:{index:3,mood:-9},result:'شعر سكان السهول بأن العاصمة تتجاهلهم.'}]},
 {id:'border',tag:'الأمن القومي',title:'توتر على الحدود الشرقية',text:'تحركات عسكرية قرب الحدود. يطلب الجيش توجيهًا واضحًا.',choices:[{label:'تعزيز الحدود',effects:{treasury:-40,stability:6},army:{readiness:8,morale:5},nation:{index:2,relation:-12},result:'انتشرت القوات سريعًا وارتفعت جاهزية الحدود.'},{label:'إرسال وفد دبلوماسي',effects:{treasury:-5,stability:2,approval:2},nation:{index:2,relation:14,trade:5},result:'وافق الطرفان على محادثات مباشرة لخفض التوتر.'},{label:'عدم التصعيد',effects:{treasury:4,stability:-5},army:{morale:-6},result:'هدأ الموقف مؤقتًا، لكن قادة الجيش أبدوا قلقهم.'}]},
 {id:'school',tag:'التعليم',title:'تعليم رقمي لكل طالب',text:'خطة لتوفير أجهزة ومنصة تعليمية لـ140 ألف طالب.',choices:[{label:'تمويل كامل',effects:{treasury:-72,approval:8,gdp:.4},groups:{students:14,professionals:4},ministry:{key:'education',performance:10},result:'بدأ توزيع الأجهزة وتدريب المعلمين في كل المدن.'},{label:'تجربة في مدينتين',effects:{treasury:-24,approval:3,gdp:.1},groups:{students:5},result:'انطلقت التجربة في العاصمة وميناء النور.'},{label:'رفض الخطة',effects:{approval:-4},groups:{students:-10},result:'عبّر الطلاب والمعلمون عن خيبة أملهم.'}]},
 {id:'tax',tag:'المالية',title:'ضريبة أرباح تصاعدية',text:'الخزانة تحتاج موارد جديدة، والمقترح يرفع ضريبة كبار الأرباح.',choices:[{label:'إقرار الضريبة',effects:{treasury:85,approval:4,stability:1,gdp:-.2},groups:{elite:-15,workers:6,farmers:5},result:'زادت إيرادات الدولة، وبدأت النخبة حملة معارضة صامتة.'},{label:'ضريبة مؤقتة',effects:{treasury:38,approval:1},groups:{elite:-6},result:'قبل رجال الأعمال الحل المؤقت على مضض.'},{label:'رفض الضريبة',effects:{treasury:-8,approval:-3},groups:{elite:7},result:'حافظ المستثمرون على دعمهم، لكن العجز بقي قائمًا.'}]},
 {id:'housing',tag:'المدن',title:'أزمة الإيجارات في العاصمة',text:'ارتفعت الإيجارات 18% وأصبح السكن عبئًا على الأسر الشابة.',choices:[{label:'بناء 20 ألف وحدة',effects:{treasury:-105,approval:10,inflation:-.5},city:{index:0,services:8,mood:8},result:'أُعلن أكبر مشروع إسكان في تاريخ المملكة.'},{label:'دعم الإيجار',effects:{treasury:-42,approval:6,inflation:.3},groups:{workers:7,students:5},result:'وصل الدعم إلى الأسر المؤهلة خلال أسابيع.'},{label:'ترك السوق',effects:{gdp:.2,approval:-7},groups:{merchants:5,workers:-8},result:'استمرت الأسعار في الارتفاع وتزايد غضب السكان.'}]}
];
const citizenNames=['عمر الخطيب','نور عبدالسلام','يوسف حمدان','سارة مراد','آدم منصور','ليلى سعيد','مالك عمران','هالة شريف'];
const jobs=['معلّم','ممرضة','مهندس','مزارع','صاحب متجر','جندي','طالبة','موظف بلدية'];
function fmt(n){return new Intl.NumberFormat('ar-EG',{maximumFractionDigits:1}).format(n)}
function save(){localStorage.setItem('kingdomState',JSON.stringify(state))}
function statCard(label,value,sub,trend=''){return `<div class="stat"><small>${label}</small><strong>${value}</strong><span class="trend ${trend>=0?'up':'down'}">${trend?`${trend>0?'▲':'▼'} ${Math.abs(trend)}`:sub}</span></div>`}
function meter(label,value){return `<div class="pulse-row"><div><span>${label}</span><b>${Math.round(value)}%</b></div><div class="meter"><i style="width:${Math.max(0,Math.min(100,value))}%"></i></div></div>`}
function renderStats(){document.querySelector('#realmStats').innerHTML=statCard('سكان المملكة',fmt(state.population),'مواطن')+statCard('الخزانة',`${fmt(state.treasury)} مليون`,'عملة ذهبية')+statCard('رضا الشعب',`${Math.round(state.approval)}%`,'المتوسط')+statCard('استقرار المملكة',`${Math.round(state.stability)}%`,'الحالة العامة')+statCard('الناتج المحلي',`${fmt(state.gdp)} مليار`,`التضخم ${fmt(state.inflation)}%`)}
function activeDecisions(){return decisions.filter((_,i)=>(i+state.turn)%decisions.length<3).slice(0,3)}
function renderDecisions(){const list=activeDecisions();document.querySelector('#decisionCount').textContent=list.length;document.querySelector('#decisionDeck').innerHTML=list.map(d=>`<div class="decision-card"><header><div><span class="tag">${d.tag}</span><h3>${d.title}</h3></div></header><p>${d.text}</p><div class="choices">${d.choices.map((c,i)=>`<button onclick="decide('${d.id}',${i})">${c.label}</button>`).join('')}</div></div>`).join('')}
function renderPulse(){const gs=Object.values(state.groups);document.querySelector('#publicMood').innerHTML=gs.slice(0,4).map(g=>meter(g.name,g.approval)).join('');const lowest=[...gs].sort((a,b)=>a.approval-b.approval)[0];document.querySelector('#sentiment').innerHTML=`أكثر الفئات قلقًا الآن: <b>${lowest.name}</b>. مستوى التأييد لديهم ${Math.round(lowest.approval)}%.`}
function renderBudget(){const items=Object.values(state.ministries);const max=Math.max(...items.map(x=>x.fund));document.querySelector('#budgetChart').innerHTML=items.map(x=>`<div class="bar-wrap"><div class="bar" style="height:${x.fund/max*100}px"></div><span>${x.name}</span></div>`).join('')}
function renderLog(){document.querySelector('#eventLog').innerHTML=state.log.slice(0,5).map(x=>`<div class="log-item"><span class="dot"></span><span>${x.text}</span><small>${x.date}</small></div>`).join('')}
function renderPeople(){document.querySelector('#classes').innerHTML=Object.values(state.groups).map(g=>`<article class="info-card"><h3>${g.name}</h3><div class="big">${fmt(g.count)}</div>${meter('الرضا',g.approval)}<div class="mini-stats"><span>متوسط الدخل</span><b>${fmt(g.income)}</b></div></article>`).join('');document.querySelector('#citizens').innerHTML=citizenNames.map((n,i)=>{const city=state.cities[i%state.cities.length],mood=Math.round((city.mood+state.approval)/2);return `<div class="citizen"><span class="avatar">${n[0]}</span><div><b>${n}</b><small>${jobs[i]} · ${city.name} · ${mood>68?'متفائل':mood>52?'متردد':'قلق'}</small></div></div>`}).join('')}
function renderMinistries(){document.querySelector('#ministryGrid').innerHTML=Object.entries(state.ministries).map(([k,m])=>`<article class="info-card"><span class="tag">ميزانية ${m.fund} مليون</span><h3>${m.name}</h3><p class="muted">الوزير: ${m.minister}</p>${meter('الأداء',m.performance)}<div class="fund"><span>تعديل التمويل</span><div><button onclick="fund('${k}',-5)">−</button> <button onclick="fund('${k}',5)">+</button></div></div></article>`).join('')}
function renderCities(){document.querySelector('#cityGrid').innerHTML=state.cities.map(c=>`<article class="info-card"><h3>${c.name}</h3><div class="big">${fmt(c.pop)} نسمة</div>${meter('فرص العمل',c.jobs)}${meter('الخدمات',c.services)}<span class="city-status">مزاج السكان ${Math.round(c.mood)}%</span></article>`).join('')}
function renderDiplomacy(){document.querySelector('#army').innerHTML=`<div class="big">${fmt(state.army.soldiers)} جندي</div>${meter('الجاهزية',state.army.readiness)}${meter('المعنويات',state.army.morale)}${meter('التسليح',state.army.equipment)}<div class="fund"><span>مناورات عسكرية — 18 مليون</span><button onclick="exercise()">تنفيذ</button></div>`;document.querySelector('#nations').innerHTML=state.nations.map((n,i)=>`<div class="nation"><div><b>${n.name}</b><small class="muted"> · تجارة ${n.trade}%</small></div><span class="relation">علاقة ${n.relation}%</span></div>`).join('')}
function renderDate(){const seasons=['الربيع','الصيف','الخريف','الشتاء'];document.querySelector('#dateLabel').textContent=`السنة ${state.year} — ${seasons[state.season]}`;let msg=state.approval>75?'الشعب يثق بقيادتك، والتوقعات مرتفعة.':state.approval>55?'المملكة مستقرة، لكن قرارات اليوم سترسم مستقبلها.':'الشارع مضطرب ومجلسك ينتظر قرارات حاسمة.';document.querySelector('#briefing').textContent=msg}
function renderAll(){renderDate();renderStats();renderDecisions();renderPulse();renderBudget();renderLog();renderPeople();renderMinistries();renderCities();renderDiplomacy();save()}
function clamp(){state.approval=Math.max(0,Math.min(100,state.approval));state.stability=Math.max(0,Math.min(100,state.stability));Object.values(state.groups).forEach(g=>g.approval=Math.max(0,Math.min(100,g.approval)));state.cities.forEach(c=>{c.mood=Math.max(0,Math.min(100,c.mood));c.services=Math.min(100,c.services)});Object.values(state.ministries).forEach(m=>m.performance=Math.max(0,Math.min(100,m.performance)))}
function decide(id,choiceIndex){const d=decisions.find(x=>x.id===id),c=d.choices[choiceIndex];Object.entries(c.effects||{}).forEach(([k,v])=>state[k]+=v);Object.entries(c.groups||{}).forEach(([k,v])=>state.groups[k].approval+=v);if(c.city)Object.entries(c.city).forEach(([k,v])=>k!=='index'&&(state.cities[c.city.index][k]+=v));if(c.army)Object.entries(c.army).forEach(([k,v])=>state.army[k]+=v);if(c.nation)Object.entries(c.nation).forEach(([k,v])=>k!=='index'&&(state.nations[c.nation.index][k]+=v));if(c.ministry)state.ministries[c.ministry.key].performance+=c.ministry.performance;state.turn++;state.log.unshift({text:`${d.title}: ${c.label}`,date:`السنة ${state.year}`});clamp();showResult(d.title,c);renderAll()}
function showResult(title,c){document.querySelector('#modalTitle').textContent=title;document.querySelector('#modalText').textContent=c.result;document.querySelector('#modalEffects').innerHTML=Object.entries(c.effects||{}).map(([k,v])=>`<span>${labels[k]||k}: ${v>0?'+':''}${v}</span>`).join('');document.querySelector('#resultDialog').showModal()}
const labels={treasury:'الخزانة',approval:'الرضا',stability:'الاستقرار',gdp:'الاقتصاد',inflation:'التضخم'};
function fund(k,v){if(v>0&&state.treasury<5)return toast('الخزانة لا تسمح');state.ministries[k].fund+=v;state.treasury-=v;state.ministries[k].performance+=v>0?1:-1;state.log.unshift({text:`تعديل تمويل وزارة ${state.ministries[k].name}`,date:`السنة ${state.year}`});clamp();renderAll();toast('تم تحديث ميزانية الوزارة')}
function exercise(){if(state.treasury<18)return toast('الخزانة لا تسمح');state.treasury-=18;state.army.readiness=Math.min(100,state.army.readiness+5);state.army.morale=Math.min(100,state.army.morale+3);state.log.unshift({text:'مناورات كبرى للقوات الملكية',date:`السنة ${state.year}`});renderAll();toast('اكتملت المناورات بنجاح')}
function advance(){if(state.paused)return;state.season++;if(state.season>3){state.season=0;state.year++}const income=36+state.gdp*1.5,expense=Object.values(state.ministries).reduce((a,m)=>a+m.fund,0)/12;state.treasury+=income-expense;state.gdp+=((state.stability-50)/500);state.inflation+=Math.random()*.4-.2;Object.values(state.groups).forEach(g=>g.approval+=(state.approval-g.approval)*.06+(Math.random()*2-1));state.cities.forEach(c=>c.mood+=(state.approval-c.mood)*.04+(Math.random()*2-1));if(state.treasury<0){state.approval-=3;state.stability-=2;state.log.unshift({text:'تحذير: عجز في الخزانة الملكية',date:`السنة ${state.year}`})}clamp();renderAll()}
function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view,.nav').forEach(x=>x.classList.remove('active'));document.querySelector(`#${b.dataset.view}`).classList.add('active');document.querySelector(`.nav[data-view="${b.dataset.view}"]`)?.classList.add('active');scrollTo(0,0)});
document.querySelectorAll('.speed').forEach(b=>b.onclick=()=>{state.speed=+b.dataset.speed;document.querySelectorAll('.speed').forEach(x=>x.classList.toggle('active',x===b));save()});document.querySelector('#pauseBtn').onclick=e=>{state.paused=!state.paused;e.target.textContent=state.paused?'▶':'Ⅱ';toast(state.paused?'توقف الزمن':'استأنف الزمن')};document.querySelector('#closeDialog').onclick=()=>document.querySelector('#resultDialog').close();setInterval(()=>{for(let i=0;i<state.speed;i++)advance()},12000);renderAll();
