const firebaseConfig={apiKey:'AIzaSyC57vPKCUy7cEHT9Zb8wvKM4CqAadDRpdM',authDomain:'kingdom-of-ahmed.firebaseapp.com',projectId:'kingdom-of-ahmed',storageBucket:'kingdom-of-ahmed.firebasestorage.app',messagingSenderId:'636020426742',appId:'1:636020426742:web:da39650e90e8c8eb1229d7'};
firebase.initializeApp(firebaseConfig);
const auth=firebase.auth(),db=firebase.firestore();
const authDialog=document.querySelector('#authDialog'),accountBtn=document.querySelector('#accountBtn'),authSubmit=document.querySelector('#authSubmit'),authSwitch=document.querySelector('#authSwitch'),authError=document.querySelector('#authError');
let registerMode=false,cloudReady=false,cloudTimer=null,unsubscribeKingdoms=null,unsubscribeIncoming=null,unsubscribeOutgoing=null;
let incomingRequests=[],outgoingRequests=[],selectedKingdomId=null;

function setAuthMode(register){registerMode=register;document.querySelector('#authTitle').textContent=register?'إنشاء حساب ملكي':'دخول عالم الممالك';document.querySelector('#authHint').textContent=register?'أنشئ حسابًا مجانيًا لحفظ مملكتك على أي جهاز.':'سجّل دخولك لتحميل مملكتك واللعب مع الآخرين.';authSubmit.textContent=register?'إنشاء الحساب':'تسجيل الدخول';authSwitch.textContent=register?'لدي حساب بالفعل':'إنشاء حساب جديد';authError.textContent=''}
accountBtn.onclick=()=>{if(auth.currentUser){if(confirm('هل تريد تسجيل الخروج من المملكة؟'))auth.signOut()}else{setAuthMode(false);authDialog.showModal()}};
document.querySelector('#closeAuth').onclick=()=>authDialog.close();
authSwitch.onclick=()=>setAuthMode(!registerMode);
authSubmit.onclick=async()=>{const email=document.querySelector('#authEmail').value.trim(),password=document.querySelector('#authPassword').value;authError.textContent='';if(!email||password.length<6){authError.textContent='اكتب بريدًا صحيحًا وكلمة سر من 6 أحرف على الأقل.';return}authSubmit.disabled=true;try{if(registerMode)await auth.createUserWithEmailAndPassword(email,password);else await auth.signInWithEmailAndPassword(email,password);authDialog.close()}catch(error){const messages={'auth/email-already-in-use':'البريد مسجّل بالفعل. اختر تسجيل الدخول.','auth/invalid-email':'البريد الإلكتروني غير صحيح.','auth/invalid-credential':'البريد أو كلمة السر غير صحيحة.','auth/weak-password':'كلمة السر ضعيفة؛ استخدم 6 أحرف على الأقل.','auth/too-many-requests':'محاولات كثيرة. انتظر قليلًا ثم حاول مجددًا.'};authError.textContent=messages[error.code]||'تعذر الاتصال الآن. حاول مرة أخرى.'}finally{authSubmit.disabled=false}};

function publicKingdomData(user){return{ownerId:user.uid,kingName:state.kingName||'ملك جديد',kingdomName:state.kingdomName||'مملكة جديدة',power:playerPower(),level:state.level||1,approval:Math.round(state.approval),updatedAt:firebase.firestore.FieldValue.serverTimestamp()}}
window.saveCloudState=function(){const user=auth.currentUser;if(!user||!cloudReady)return;clearTimeout(cloudTimer);cloudTimer=setTimeout(async()=>{try{await Promise.all([db.collection('users').doc(user.uid).set({email:user.email,state:JSON.parse(JSON.stringify(state)),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true}),db.collection('kingdoms').doc(user.uid).set(publicKingdomData(user),{merge:true})]);accountBtn.classList.remove('saving')}catch(e){accountBtn.classList.remove('saving');toast('تعذر الحفظ السحابي مؤقتًا')}},700);accountBtn.classList.add('saving')};
function watchKingdoms(user){if(unsubscribeKingdoms)unsubscribeKingdoms();unsubscribeKingdoms=db.collection('kingdoms').onSnapshot(snapshot=>{window.onlineKingdoms=snapshot.docs.filter(d=>d.id!==user.uid).map((d,i)=>({id:d.id,...d.data(),x:15+(i*29)%72,y:20+(i*37)%65}));renderWorld()},()=>toast('تعذر تحديث العالم الآن'))}
function requestDocId(fromUid,toUid){return`${fromUid}_${toUid}`}
function requestForKingdom(id){return outgoingRequests.find(r=>r.toUid===id)||incomingRequests.find(r=>r.fromUid===id)}
function renderAllianceRequests(){const box=document.querySelector('#allianceRequests');if(!box)return;if(!auth.currentUser){box.innerHTML='<p class="muted">سجّل الدخول لعرض الطلبات.</p>';return}const incoming=incomingRequests.filter(r=>r.status==='pending');const accepted=[...incomingRequests,...outgoingRequests].filter((r,i,a)=>r.status==='accepted'&&a.findIndex(x=>x.id===r.id)===i);if(!incoming.length&&!accepted.length){box.innerHTML='<p class="muted">لا توجد طلبات حاليًا. اضغط على أي مملكة حقيقية لإرسال طلب.</p>';return}box.innerHTML=[...incoming.map(r=>`<div class="request-card"><b>${r.fromKingdom||'مملكة جديدة'}</b><p class="muted">${r.fromKing||'ملك'} يطلب التحالف معك.</p><div class="request-actions"><button onclick="respondAlliance('${r.id}','accepted')">قبول</button><button class="reject" onclick="respondAlliance('${r.id}','rejected')">رفض</button></div></div>`),...accepted.map(r=>`<div class="request-card"><span class="status-pill">حليف</span> <b>${r.fromUid===auth.currentUser.uid?r.toKingdom:r.fromKingdom}</b></div>`)].join('')}
function watchAllianceRequests(user){if(unsubscribeIncoming)unsubscribeIncoming();if(unsubscribeOutgoing)unsubscribeOutgoing();unsubscribeIncoming=db.collection('allianceRequests').where('toUid','==',user.uid).onSnapshot(s=>{incomingRequests=s.docs.map(d=>({id:d.id,...d.data()}));syncAcceptedAlliance(user);renderAllianceRequests()},()=>toast('تعذر تحميل طلبات التحالف'));unsubscribeOutgoing=db.collection('allianceRequests').where('fromUid','==',user.uid).onSnapshot(s=>{outgoingRequests=s.docs.map(d=>({id:d.id,...d.data()}));syncAcceptedAlliance(user);renderAllianceRequests()},()=>toast('تعذر تحميل طلبات التحالف'))}
function syncAcceptedAlliance(user){const accepted=[...incomingRequests,...outgoingRequests].find(r=>r.status==='accepted');if(!accepted)return;const allyName=accepted.fromUid===user.uid?accepted.toKingdom:accepted.fromKingdom;if(state.alliance!==`تحالف مع ${allyName}`){state.alliance=`تحالف مع ${allyName}`;save();renderWorld()}}
window.showKingdomProfile=function(id){const kingdom=(window.onlineKingdoms||[]).find(k=>k.id===id);if(!kingdom)return toast('لم تعد المملكة متصلة');selectedKingdomId=id;document.querySelector('#profileKingdomName').textContent=kingdom.kingdomName||'مملكة جديدة';document.querySelector('#profileKingName').textContent=`الحاكم: ${kingdom.kingName||'ملك جديد'}`;document.querySelector('#profilePower').textContent=kingdom.power||0;document.querySelector('#profileLevel').textContent=kingdom.level||1;document.querySelector('#profileApproval').textContent=`${kingdom.approval||0}%`;const req=requestForKingdom(id),btn=document.querySelector('#sendAllianceBtn'),status=document.querySelector('#allianceActionStatus');btn.disabled=!!req;status.textContent=req?req.status==='accepted'?'أنتما حليفان بالفعل':req.status==='rejected'?'تم رفض الطلب السابق':'طلب التحالف قيد الانتظار':'';btn.textContent=req?'تم إرسال الطلب':'إرسال طلب تحالف';document.querySelector('#kingdomDialog').showModal()};
document.querySelector('#closeKingdom').onclick=()=>document.querySelector('#kingdomDialog').close();
document.querySelector('#sendAllianceBtn').onclick=async()=>{const user=auth.currentUser,kingdom=(window.onlineKingdoms||[]).find(k=>k.id===selectedKingdomId);if(!user||!kingdom)return toast('سجّل الدخول أولًا');const id=requestDocId(user.uid,kingdom.id);try{await db.collection('allianceRequests').doc(id).set({fromUid:user.uid,toUid:kingdom.id,fromKingdom:state.kingdomName||'مملكة جديدة',fromKing:state.kingName||'ملك جديد',toKingdom:kingdom.kingdomName||'مملكة جديدة',status:'pending',createdAt:firebase.firestore.FieldValue.serverTimestamp()});document.querySelector('#kingdomDialog').close();toast('تم إرسال طلب التحالف')}catch(e){toast('تعذر إرسال الطلب. تأكد من نشر قواعد Firestore الجديدة')}};
window.respondAlliance=async function(id,status){try{await db.collection('allianceRequests').doc(id).update({status,respondedAt:firebase.firestore.FieldValue.serverTimestamp()});toast(status==='accepted'?'تم قبول التحالف':'تم رفض الطلب')}catch(e){toast('تعذر تحديث الطلب')}};
auth.onAuthStateChanged(async user=>{cloudReady=false;if(!user){accountBtn.textContent='دخول اللاعبين';accountBtn.classList.remove('online');window.onlineKingdoms=[];incomingRequests=[];outgoingRequests=[];[unsubscribeKingdoms,unsubscribeIncoming,unsubscribeOutgoing].forEach(fn=>{if(fn)fn()});unsubscribeKingdoms=unsubscribeIncoming=unsubscribeOutgoing=null;renderWorld();renderAllianceRequests();return}accountBtn.textContent='متصل ●';accountBtn.classList.add('online');try{const snap=await db.collection('users').doc(user.uid).get();if(snap.exists&&snap.data().state){state=snap.data().state;localStorage.setItem('kingdomState',JSON.stringify(state));renderAll();toast('تم تحميل مملكتك من السحابة')}else{await db.collection('users').doc(user.uid).set({email:user.email,state:JSON.parse(JSON.stringify(state)),createdAt:firebase.firestore.FieldValue.serverTimestamp()});toast('تم إنشاء حسابك الملكي')}cloudReady=true;await db.collection('kingdoms').doc(user.uid).set(publicKingdomData(user),{merge:true});watchKingdoms(user);watchAllianceRequests(user)}catch(e){toast('تعذر تحميل بيانات المملكة');cloudReady=true}});
