const firebaseConfig={apiKey:'AIzaSyC57vPKCUy7cEHT9Zb8wvKM4CqAadDRpdM',authDomain:'kingdom-of-ahmed.firebaseapp.com',projectId:'kingdom-of-ahmed',storageBucket:'kingdom-of-ahmed.firebasestorage.app',messagingSenderId:'636020426742',appId:'1:636020426742:web:da39650e90e8c8eb1229d7'};
firebase.initializeApp(firebaseConfig);
const auth=firebase.auth(),db=firebase.firestore();
const authDialog=document.querySelector('#authDialog'),accountBtn=document.querySelector('#accountBtn'),authSubmit=document.querySelector('#authSubmit'),authSwitch=document.querySelector('#authSwitch'),authError=document.querySelector('#authError');
let registerMode=false,cloudReady=false,cloudTimer=null,unsubscribeKingdoms=null;

function setAuthMode(register){registerMode=register;document.querySelector('#authTitle').textContent=register?'إنشاء حساب ملكي':'دخول عالم الممالك';document.querySelector('#authHint').textContent=register?'أنشئ حسابًا مجانيًا لحفظ مملكتك على أي جهاز.':'سجّل دخولك لتحميل مملكتك واللعب مع الآخرين.';authSubmit.textContent=register?'إنشاء الحساب':'تسجيل الدخول';authSwitch.textContent=register?'لدي حساب بالفعل':'إنشاء حساب جديد';authError.textContent=''}
accountBtn.onclick=()=>{if(auth.currentUser){if(confirm('هل تريد تسجيل الخروج من المملكة؟'))auth.signOut()}else{setAuthMode(false);authDialog.showModal()}};
document.querySelector('#closeAuth').onclick=()=>authDialog.close();
authSwitch.onclick=()=>setAuthMode(!registerMode);
authSubmit.onclick=async()=>{const email=document.querySelector('#authEmail').value.trim(),password=document.querySelector('#authPassword').value;authError.textContent='';if(!email||password.length<6){authError.textContent='اكتب بريدًا صحيحًا وكلمة سر من 6 أحرف على الأقل.';return}authSubmit.disabled=true;try{if(registerMode)await auth.createUserWithEmailAndPassword(email,password);else await auth.signInWithEmailAndPassword(email,password);authDialog.close()}catch(error){const messages={'auth/email-already-in-use':'البريد مسجّل بالفعل. اختر تسجيل الدخول.','auth/invalid-email':'البريد الإلكتروني غير صحيح.','auth/invalid-credential':'البريد أو كلمة السر غير صحيحة.','auth/weak-password':'كلمة السر ضعيفة؛ استخدم 6 أحرف على الأقل.','auth/too-many-requests':'محاولات كثيرة. انتظر قليلًا ثم حاول مجددًا.'};authError.textContent=messages[error.code]||'تعذر الاتصال الآن. حاول مرة أخرى.'}finally{authSubmit.disabled=false}};

function publicKingdomData(user){return{ownerId:user.uid,kingName:state.kingName||'ملك جديد',kingdomName:state.kingdomName||'مملكة جديدة',power:playerPower(),level:state.level||1,approval:Math.round(state.approval),updatedAt:firebase.firestore.FieldValue.serverTimestamp()}}
window.saveCloudState=function(){const user=auth.currentUser;if(!user||!cloudReady)return;clearTimeout(cloudTimer);cloudTimer=setTimeout(async()=>{try{await Promise.all([db.collection('users').doc(user.uid).set({email:user.email,state:JSON.parse(JSON.stringify(state)),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true}),db.collection('kingdoms').doc(user.uid).set(publicKingdomData(user),{merge:true})]);accountBtn.classList.remove('saving')}catch(e){accountBtn.classList.remove('saving');toast('تعذر الحفظ السحابي مؤقتًا')}},700);accountBtn.classList.add('saving')};
function watchKingdoms(user){if(unsubscribeKingdoms)unsubscribeKingdoms();unsubscribeKingdoms=db.collection('kingdoms').onSnapshot(snapshot=>{window.onlineKingdoms=snapshot.docs.filter(d=>d.id!==user.uid).map((d,i)=>({id:d.id,...d.data(),x:15+(i*29)%72,y:20+(i*37)%65}));renderWorld()},()=>toast('تعذر تحديث العالم الآن'))}
auth.onAuthStateChanged(async user=>{cloudReady=false;if(!user){accountBtn.textContent='دخول اللاعبين';accountBtn.classList.remove('online');window.onlineKingdoms=[];if(unsubscribeKingdoms){unsubscribeKingdoms();unsubscribeKingdoms=null}renderWorld();return}accountBtn.textContent='متصل ●';accountBtn.classList.add('online');try{const snap=await db.collection('users').doc(user.uid).get();if(snap.exists&&snap.data().state){state=snap.data().state;localStorage.setItem('kingdomState',JSON.stringify(state));renderAll();toast('تم تحميل مملكتك من السحابة')}else{await db.collection('users').doc(user.uid).set({email:user.email,state:JSON.parse(JSON.stringify(state)),createdAt:firebase.firestore.FieldValue.serverTimestamp()});toast('تم إنشاء حسابك الملكي')}cloudReady=true;await db.collection('kingdoms').doc(user.uid).set(publicKingdomData(user),{merge:true});watchKingdoms(user)}catch(e){toast('تعذر تحميل بيانات المملكة');cloudReady=true}});
