Object.assign(state,{coins:state.coins??240,xp:state.xp??0,level:state.level??1,kingName:state.kingName??'',kingdomName:state.kingdomName??'',alliance:state.alliance??null,lastDaily:state.lastDaily??'',inventory:state.inventory??[]});
const rivals=[{name:'مملكة الصقور',king:'الملك سيف',power:86,x:18,y:25},{name:'إمبراطورية النور',king:'الملكة ليان',power:79,x:72,y:21},{name:'اتحاد الواحات',king:'الأمير راشد',power:67,x:83,y:70},{name:'جمهورية البحر',king:'الحاكم مالك',power:61,x:25,y:76},{name:'حصون الجبل',king:'الملكة نور',power:55,x:50,y:48}];
const shopItems=[{id:'banner',icon:'🚩',name:'راية التاج الذهبية',text:'مظهر ملكي خاص لمملكتك',price:90},{id:'advisor',icon:'🧙',name:'المستشار الحكيم',text:'+5 استقرار فوري',price:120},{id:'trade',icon:'🚢',name:'قافلة تجارية',text:'+30 مليون للخزانة',price:75},{id:'guard',icon:'🛡️',name:'الحرس الملكي',text:'+6 جاهزية للجيش',price:110},{id:'festival',icon:'🎉',name:'مهرجان المملكة',text:'+7 رضا شعبي',price:95},{id:'boost',icon:'⚡',name:'دفعة الخبرة',text:'+80 نقطة خبرة',price:65}];
function playerPower(){return Math.round(state.gdp*3+state.army.readiness*.35+state.stability*.25+state.level*4)}
function addXp(n){state.xp+=n;while(state.xp>=state.level*100){state.xp-=state.level*100;state.level++;state.coins+=50;toast(`وصلت للمستوى ${state.level}`)}save()}
function renderWorld(){const map=document.querySelector('#worldMap');if(!map)return;const own={name:state.kingdomName||'مملكة أحمد',king:state.kingName||'أحمد',power:playerPower(),x:49,y:79};const live=(window.onlineKingdoms||[]).map(x=>({name:x.kingdomName,king:x.kingName,power:x.power||0,x:x.x,y:x.y,online:true}));const others=live.length?live:rivals,all=[own,...others];map.innerHTML=all.map((r,i)=>`<button class="kingdom-node ${i===0?'you':''} ${r.online?'live':''}" style="left:${r.x}%;top:${r.y}%" onclick="${i===0?"toast('هذه مملكتك')":r.online?`toast('مملكة لاعب حقيقي متصلة')`:`challenge(${i-1})`}"><b>${r.name}</b><small>${r.online?'● متصل · ':''}قوة ${r.power}</small></button>`).join('');document.querySelector('#playerLevel').textContent=state.level;document.querySelector('#playerXp').textContent=`${state.xp} / ${state.level*100} خبرة`;document.querySelector('#leaderboard').innerHTML=[...others,own].sort((a,b)=>b.power-a.power).map((r,i)=>`<div class="rank-row"><span class="rank-num">${i+1}</span><div><b>${r.name}</b><small class="muted"> · ${r.king}${r.online?' · متصل':''}</small></div><strong>${r.power}</strong></div>`).join('');document.querySelector('#tradeMarket').innerHTML=`<div class="market-row"><span>تصدير الحبوب لاتحاد الواحات</span><button onclick="trade(18,15)">تنفيذ</button></div><div class="market-row"><span>معدات من جمهورية البحر</span><button onclick="trade(-12,22)">شراء</button></div><div class="market-row"><span>طريق الحرير مع إمبراطورية النور</span><button onclick="trade(28,30)">اتفاق</button></div>`;document.querySelector('#alliancePanel').innerHTML=state.alliance?`<div class="alliance-box"><span class="online-dot"></span><b>${state.alliance}</b><p class="muted">3 ممالك متصلة · حماية تجارية +8%</p><button class="text-btn" onclick="leaveAlliance()">مغادرة التحالف</button></div>`:`<div class="alliance-box"><b>تحالف التاج الشرقي</b><p class="muted">تعاون دفاعي وتجاري بين الممالك الصاعدة.</p><button class="shop-buy" onclick="joinAlliance()">طلب الانضمام</button></div>`}
function challenge(i){const r=rivals[i],chance=playerPower()/(playerPower()+r.power);if(Math.random()<chance){const loot=20+Math.floor(Math.random()*25);state.treasury+=loot;state.coins+=15;state.army.readiness-=5;addXp(35);showResult('انتصار ملكي',{result:`انتصر جيشك أمام ${r.name} وربح ${loot} مليون و15 ذهب.`,effects:{treasury:loot}})}else{state.treasury-=15;state.army.readiness-=8;state.stability-=2;addXp(12);showResult('تراجع تكتيكي',{result:`لم تنجح الحملة أمام ${r.name}. عاد الجيش لإعادة التنظيم.`,effects:{treasury:-15,stability:-2}})}clamp();renderAll()}
function trade(money,xp){state.treasury+=money;state.coins+=money>0?4:0;addXp(xp);state.log.unshift({text:'صفقة في السوق العالمي',date:`السنة ${state.year}`});renderAll();toast('تمت الصفقة')}
function joinAlliance(){state.alliance='تحالف التاج الشرقي';state.stability=Math.min(100,state.stability+3);addXp(25);renderAll();toast('تم قبول مملكتك')}
function leaveAlliance(){state.alliance=null;renderAll();toast('غادرت التحالف')}
function refreshWorld(){rivals.forEach(r=>r.power=Math.max(45,r.power+Math.floor(Math.random()*7)-3));renderWorld();toast('تم تحديث العالم')}
function renderShop(){document.querySelector('#coinBalance').textContent=state.coins;document.querySelector('#shopGrid').innerHTML=shopItems.map(x=>`<article class="info-card"><div class="shop-icon">${x.icon}</div><h3>${x.name}</h3><p class="muted">${x.text}</p><button class="shop-buy" ${state.inventory.includes(x.id)?'disabled':''} onclick="buyItem('${x.id}')">${state.inventory.includes(x.id)?'تم الشراء':`${x.price} ذهب`}</button></article>`).join('');const today=new Date().toDateString(),btn=document.querySelector('#dailyReward');btn.disabled=state.lastDaily===today;btn.textContent=btn.disabled?'تم الاستلام اليوم':'استلام 40 ذهب'}
function buyItem(id){const x=shopItems.find(a=>a.id===id);if(state.coins<x.price)return toast('رصيد الذهب غير كافٍ');state.coins-=x.price;state.inventory.push(id);if(id==='advisor')state.stability+=5;if(id==='trade')state.treasury+=30;if(id==='guard')state.army.readiness+=6;if(id==='festival')state.approval+=7;if(id==='boost')addXp(80);clamp();renderAll();toast(`تم شراء ${x.name}`)}
function claimDaily(){const today=new Date().toDateString();if(state.lastDaily===today)return;state.lastDaily=today;state.coins+=40;addXp(20);renderAll();toast('حصلت على 40 ذهب و20 خبرة')}
function startRealm(){state.kingName=document.querySelector('#kingNameInput').value.trim()||'أحمد';state.kingdomName=document.querySelector('#kingdomNameInput').value.trim()||'مملكة أحمد';document.querySelector('#welcomeDialog').close();save();renderAll();toast('مرحبًا بك في عالم الممالك')}
const renderAllBase=renderAll;renderAll=function(){renderAllBase();renderWorld();renderShop()};renderWorld();renderShop();if(!state.kingName)setTimeout(()=>document.querySelector('#welcomeDialog').showModal(),250);
